setInterval(() => {
const quotes = ["Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.", 
    "You are never too old to set another goal or to dream a new dream.", 
    "Act as if what you do makes a difference. It does.", 
    "Success usually comes to those who are too busy to be looking for it.", 
    "Don’t watch the clock, do what it does. Keep going.", 
    "The future belongs to those who believe in the beauty of their dreams.", 
    "The only limit to our realization of tomorrow is our doubts of today.", 
    "It does not matter how slowly you go as long as you do not stop.", 
    "You are braver than you believe, stronger than you seem, and smarter than you think.", 
    "What you get by achieving your goals is not as important as what you become by achieving your goals.", 
    "Perseverance is not a long race, it is many short races one after the other.", 
    "Your time is limited, don't waste it living someone else's life.", 
    "The best way to predict the future is to create it.", 
    "Don't be afraid to give up the good to go for the great.", 
    "The only place where success comes before work is in the dictionary.", 
    "Don't wait. The time will never be just right.", 
    "The harder you work for something, the greater you'll feel when you achieve it.", 
    "If you can dream it, you can achieve it.", 
    "It always seems impossible until it’s done.",
    "Failure is not the opposite of success, it’s part of success.", 
    "The only way to achieve the impossible is to believe it is possible.", 
    "Dream big and dare to fail.", 
    "Success is walking from failure to failure with no loss of enthusiasm.", 
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", 
    "Your limitation—it’s only your imagination.", 
    "Push yourself, because no one else is going to do it for you.", 
    "Great things never come from comfort zones.", 
    "Dream it. Wish it. Do it.", 
    "Success doesn’t just find you. You have to go out and get it.", 
    "The harder you work, the luckier you get.", 
    "Do something today that your future self will thank you for.",
    "Little things make big days.", 
    "Don’t stop when you’re tired. Stop when you’re done.", 
    "Wake up with determination. Go to bed with satisfaction.", 
    "Do what you can with all you have, wherever you are.", 
    "Dream bigger. Do bigger.", 
    "It’s going to be hard, but hard does not mean impossible.", 
    "Don’t wait for opportunity. Create it.", 
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", 
    "The key to success is to focus on goals, not obstacles.", 
    "Dream big, work hard, stay focused, and surround yourself with good people.", 
    "Your only limit is your mind.", "Good things come to those who hustle.", 
    "Work hard in silence, let success be your noise.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart."];

    console.log(quotes[Math.floor(Math.random() * quotes.length)]);

    // console.log(quotes.indexOf("Your time is limited, don't waste it living someone else's life."));

}, 100);